# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.1-6-gd28f504
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
rebel_module_groups: []
repo_description: Modules related to a cooperative registry (subscribtion requests,
  share transfer, ...).
repo_name: Cooperative
repo_slug: cooperative
travis_apt_packages: []
travis_apt_sources: []
